### ISSUE TITLE
💡신청페이지

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#17]
학년
- 피그마에는 입력받는 칸..
 ![스크린샷 2023-01-15 오후 3 09 02](https://user-images.githubusercontent.com/78739194/212525713-17e72bf6-2109-4304-b7e1-c14b320c03d1.png)
- option?

예외처리
- 투어학생 수 : 10~100
- 신청자 연락처  : '-' 입력 
- 개인정보 동의  : 거부시 제출불가

**Comment by ustar1210** [comment]
기타도 넣어놨는데 그냥 학년은 선택으로 하면 안되나요,,? 헤헤
예외처리는 추가해놓을게용

**Comment by seochan99** [comment]
그러게 저건 학교에 함물어봐야할둣!!

**Comment by ustar1210** [comment]
예외처리 해놓았는데 지금 코드는
투어학생수 1-~100이 아닐때 : 다시 신청 폼으로 리디렉션
신청자연락처 : 010-1111-1111 이든 01011111111이든 다 01011111111로 저장되게 설정
개인정보 동의 : 거부시 다시 신청폼으로 리디렉션

이렇게 해놨는데
만약에 개인정보 동의 거부시 리디렉션되면서 "개인정보동의를 해주세요"
투어 학생수 범위 밖일 때 "투어 학생 수를 확인해주세요"
같은 에러코드를 출력하게 해야하는지도 궁금... 그러면 코드가 아주 길어질것같아서 ^^ ㅋㅋㅋㅋ
근데 하라면 해야죠...

**Comment by seochan99** [comment]
ㄴㄴㄴㄴㄴ 그냥 개인정보 동의 안하면 프론트단에서 알림창뜨고 리다이렉션되게 만들면될듯!!! 한거보고 내가 알림창떠서 POST못보내게 할께

**Comment by ustar1210** [comment]
넵... 감사합니다...
