### ISSUE TITLE
❗️게시글 삭제 후 게시글 번호안바뀌는 문제

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#18]
![스크린샷 2023-01-15 오후 2 38 59](https://user-images.githubusercontent.com/78739194/212524723-7151c11d-99fe-438d-9345-2b11a5b6c251.png)

id값을 가져 오는거라 어찌 못하나...
삭제 후 id재할당..이런방식 가능한가..

**Comment by ustar1210** [comment]
얘는 모르겠어용
