### ISSUE TITLE
❗️정기투어 가능 일 공지문 문제

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#19]
![스크린샷 2023-01-15 오후 2 40 28](https://user-images.githubusercontent.com/78739194/212524769-ed259bec-8ce0-4c50-9024-225d21f2f5b6.png)

``` python
                    <!-- [공지] 1월 정기 캠퍼스투어일은 18일 입니다. -->
                    {% for d in tour_dates %}
                    [공지] {{ d.date.month }}월 정기 캠퍼스투어일은 {{ d }} 입니다.
                    {% endfor %}
```
현재 위와 같은 코드로 
같은 [공지]를 여러번 작성하는 문제가 발생함 
![스크린샷 2023-01-15 오후 2 42 07](https://user-images.githubusercontent.com/78739194/212524812-fcceeb24-3e82-4cc6-bf70-a1d38b6babc9.png)

글이 길어져서 모바일에 이슈발생

**Comment by seochan99** [comment]
약간 1월 27,28,29일 입니다.
이런식으로 월은 한번만 뜨고 일을 뒤에 붙이는 방식으로 바꾸면 될듯함

**Comment by ustar1210** [comment]
![image](https://user-images.githubusercontent.com/96715522/212611001-d3aeaef5-91f7-4264-b4d1-6c781ae7c908.png)

수정완료했습니당 css 줄 바뀌게 맥여주세요~
