### ISSUE TITLE
❗️검토중, 신청 상태 확인하세요가 서로 바뀜 

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#20]
![스크린샷 2023-01-15 오후 2 45 37](https://user-images.githubusercontent.com/78739194/212524899-776f2d34-bb0e-48df-bd79-71c99b60b7bd.png)

글 등록하고 바로 떠야하는건 신청 상태확인하세요가아닌 검토중이 떠야함

**Comment by ustar1210** [comment]
수정완료했숨닷
