### ISSUE TITLE
❗️수정시 보호자 필요유무 예외처리

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#22]
- 현재 14세 이상이면 보호자를 안받음 
![스크린샷 2023-01-15 오후 3 18 55](https://user-images.githubusercontent.com/78739194/212526038-1d15026e-070a-480e-8975-fe1e1ebadfab.png)

- 근데.. 수정하기 누르면 아래와 같이 보호자 성명 나옴, 예외처리 필요
![스크린샷 2023-01-15 오후 3 19 25](https://user-images.githubusercontent.com/78739194/212526053-f05109ba-6e28-4f18-9f24-e0519ca596ce.png)

**Comment by ustar1210** [comment]
이부분은 regular_form 신청하기 할 때 처럼 너가 스크립트 써서 지워주세요... 14세 이상이면 안뜨고 14세 미만이면 뜨게끔...
작성자가 바꿀수도 있자나여

**Comment by seochan99** [comment]
어엉 내가 할껀데 까먹을까봐 적어둔고
