### ISSUE TITLE
❗️ 관리자 페이지 : 빨간날 설정 불가

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#33]
<img width="915" alt="스크린샷 2023-01-22 오전 12 56 52" src="https://user-images.githubusercontent.com/78739194/213875283-16870400-6d1d-4452-a0de-81a3242da434.png">

학교 행사 및 설날연휴와 같이 추가 가능한 기능이  없음
<img width="653" alt="스크린샷 2023-01-22 오전 12 58 22" src="https://user-images.githubusercontent.com/78739194/213875327-eedd799b-2d9f-4f8a-b618-e86f7fd63e03.png">

**Comment by ustar1210** [comment]
![image](https://user-images.githubusercontent.com/96715522/214019722-25a204c0-9e1a-4a3d-a015-5e7a254f796b.png)

요런식으로 구현
아무것도 입력안하면 아무것도 안뜨고, textbox에 '신정', '학교행사'등 입력하고 체크하면 달력에 문자 표시

**Comment by ustar1210** [comment]
색칠은 프론트엔드 화이팅!! 코드 확인 부탁
