### ISSUE TITLE
❗️ 만남장소 데이터 추가

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#36]
<img width="294" alt="스크린샷 2023-01-22 오전 3 09 11" src="https://user-images.githubusercontent.com/78739194/213881225-c8675ee9-5b4d-499e-a066-c548ce50780f.png">

Data 추가
<img width="637" alt="스크린샷 2023-01-22 오전 3 17 34" src="https://user-images.githubusercontent.com/78739194/213881257-b5f084c0-7a64-4413-9e77-675bba575082.png">

**Comment by ustar1210** [comment]
확인이용

**Comment by ustar1210** [comment]
정기투어에 관리자가 진행장소, 관리자메모 등록하고 승인할 수 있게끔 해놓으면서 수정했어요
단체투어 디폴트 > 정각원 앞 백년비
정기투어 디폴트 > 팔정도 코끼리상 앞
으로  구현했습니다!
