### ISSUE TITLE
!관리자 - 정기투어 페이지 디자인 요청

### ISSUE THREAD

**Issue by ustar1210** [ustar1210/Donggam#41]
![image](https://user-images.githubusercontent.com/96715522/213992028-759baf58-3b1e-4c52-b5c4-27f1a747dd2d.png)

혹쉬 이미 완성했던 페이지라 빼먹을까봐...
부탁드려용~

**Comment by seochan99** [comment]
<img width="1401" alt="스크린샷 2023-01-25 오전 1 26 32" src="https://user-images.githubusercontent.com/78739194/214350159-a4afb13b-291c-4f5e-b167-22ce58726ead.png">
완료!

<img width="1293" alt="스크린샷 2023-01-25 오전 1 26 56" src="https://user-images.githubusercontent.com/78739194/214350244-f253349d-dcb5-4522-999c-e8834391e86d.png">

**Comment by ustar1210** [comment]
고생해써용
