### ISSUE TITLE
❗️ 휴일 초기화 기능

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#45]
<img width="1298" alt="스크린샷 2023-01-25 오전 1 22 43" src="https://user-images.githubusercontent.com/78739194/214349261-6148dfb0-9824-4739-94d6-3f4bb429264c.png">

2월달 휴일지정하고 휴일 초기화 누르면 초기화가 안됨

1월에서는 잘 작동함

- 휴일 초기화 및 초기화 기능이 선택한 날에 대해서 작동하도록 가능한지..?

**Comment by ustar1210** [comment]
![image](https://user-images.githubusercontent.com/96715522/214619311-0869a884-6401-4ccc-8647-40811327a3a3.png)

초기화 버튼을 살려보려고 했는데 리다이렉션 에러가 좀 남
1. 2월에서 초기화 때리면 2월만 초기화가 아니라 전체 db에서 초기화가 되어버림
2. 2월에서 초기화 때리면 초기화 끝난 후에 2월 달력으로 리디렉션 되어야하는데 현재일 기준 월로 리디렉션 됨... 근데 개선 방안이 딱히 생각 안남

그래서 걍 초기화 없애고 선택삭제 구현했습니다... 에러 또 있으면 말해주셍여
