### ISSUE TITLE
❗️ 이전 날짜  신청하면 에러화면뜸

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#47]
- <img width="608" alt="스크린샷 2023-01-25 오전 1 50 06" src="https://user-images.githubusercontent.com/78739194/214355931-2f61971c-367c-4c68-915a-4786f6ef5a75.png">
위 내용 제출시

- <img width="1014" alt="스크린샷 2023-01-25 오전 1 49 46" src="https://user-images.githubusercontent.com/78739194/214355868-196cd48a-e8d4-4cee-9b36-ac837e93928c.png">
위와 같은 에러발생

- <img width="609" alt="스크린샷 2023-01-25 오전 1 50 30" src="https://user-images.githubusercontent.com/78739194/214356032-6efbc380-9710-4101-85fd-0f168db94842.png">

새로 고침하면 잘 먹혀있음
예외처리 필요해보임.

++)이전 날짜라서 뜨는 에러는 아닌거같음..

<img width="723" alt="스크린샷 2023-01-25 오전 1 55 20" src="https://user-images.githubusercontent.com/78739194/214357173-9cc97239-1d60-4e6d-9a03-a6ca037d28e4.png">

<img width="834" alt="스크린샷 2023-01-25 오전 1 54 59" src="https://user-images.githubusercontent.com/78739194/214357203-99ccabed-afe8-4ebe-a87c-024ced7f3d75.png">

**Comment by seochan99** [comment]
<img width="687" alt="스크린샷 2023-01-25 오전 1 57 12" src="https://user-images.githubusercontent.com/78739194/214357604-eb1c64c0-9979-4d8a-b3bd-7f4c25b42aeb.png">

**Comment by ustar1210** [comment]
해결했습니당!
