### ISSUE TITLE
❗️ 관리자가 관리자페이지에서 신청하기 누르면 에러뜸

### ISSUE THREAD

**Issue by seochan99** [ustar1210/Donggam#48]
<img width="304" alt="스크린샷 2023-01-25 오전 2 43 59" src="https://user-images.githubusercontent.com/78739194/214368461-420cd430-2dc2-48c3-a055-f793842eba7d.png">
관리자한테서는 a가 아닌 p태그 하는게 방법일지도.. 
<img width="987" alt="스크린샷 2023-01-25 오전 2 45 01" src="https://user-images.githubusercontent.com/78739194/214368504-d8dcd956-4cf7-4949-bdf4-9afaee9383d2.png">

**Comment by ustar1210** [comment]
에러는 해결했는데 신청폼으로 가게끔 해놨음
근데 이게 맞음..? 그냥 p태그 써서 눌러도 아무 일도 안생기게 하는게 더 맞지않음?

**Comment by seochan99** [comment]
ㅇㅇㅇ 그게 맞는듯! P로 바꿀께
